package yuma140902.hundredsofores;

import java.io.File;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraftforge.common.config.Configuration;
import yuma140902.hundredsofores.creativeTabs.HOOCreativeTab;
import yuma140902.hundredsofores.orefamilies.core.OreFamilies;
import yuma140902.hundredsofores.worldGen.WorldGenerators;

@Mod(modid = ModHundredsOfOres.MOD_ID, useMetadata = true)
public class ModHundredsOfOres {
	@Mod.Metadata
	public static ModMetadata modMetadata;
	
	@Mod.Instance
	public static ModHundredsOfOres INSTANCE;
	
	public static final String MOD_ID = "hundredsOfOres";
	public static final String MOD_NAME = "鉱石追加MOD HundredsOfOres";
	public static final String MOD_VERSION = "mc1.7.10_1.0.0";
	public static final CreativeTabs MOD_CREATIVETAB = new HOOCreativeTab();
	private static final String CONFIG_FILE_NAME = "config\\" + MOD_NAME + ".cfg";
	public static final Configuration CONFIGURATION = new Configuration(new File(CONFIG_FILE_NAME));
	
	private void loadModMetadata(ModMetadata modMetadata) {
		modMetadata.modId = MOD_ID;
		modMetadata.name = MOD_NAME;
		modMetadata.version = MOD_VERSION;
		modMetadata.authorList.add("yuma140902");
		modMetadata.description = "さまざまな鉱石を追加するMODです。";
		modMetadata.url = "";
		modMetadata.autogenerated = false;
	}
	
	private void loadConfig() {
//		try {
//			CONFIGURATION.load();
//		}
//		finally {
//			CONFIGURATION.save();
//		}
	}
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		loadModMetadata(modMetadata);
		loadConfig();
		
		MyBlocks.register();
		MyItems.register();
		OreFamilies.register();
		
		OreFamilies.loadConfigs();
	}
	
	@EventHandler
	public void Init(FMLInitializationEvent event) {
		OreFamilies.init();
		OreFamilies.registerToWorldGenerators();
		WorldGenerators.register();
	}
}
